apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  creationTimestamp: null
  name: component
  namespace: application-service
spec:
  params:
  - name: git-revision
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      annotations:
        build.appstudio.openshift.io/application: zz
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: component
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      creationTimestamp: null
      generateName: component-
      labels:
        build.appstudio.openshift.io/application: zz
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: component
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      namespace: application-service
    spec:
      params:
      - name: git-url
        value: https://github.com/jduimovich/single-container-app
      - name: output-image
        value: quay.io/redhat-appstudio/user-workload:application-service-component-$(tt.params.git-revision)
      pipelineRef:
        bundle: quay.io/redhat-appstudio/build-templates-bundle:510fa6e99f1fa1f816c96354bbaf1ad155c6d9c3
        name: docker-build
      workspaces:
      - name: workspace
        persistentVolumeClaim:
          claimName: appstudio
        subPath: component/$(tt.params.git-revision)
    status: {}
status: {}
